Primer Commit
Bedu2/CH2Red pull request #1
Opened 2018-09-26 04:03 UTC by pereyragamboa

header
reducer usuarios
tabla usuarios

2018-09-26 17:44 UTC, Chipss approved these changes

2018-09-26 22:15 UTC, RodolfoSaldivar requested changes

2018-09-26 22:15 UTC, RodolfoSaldivar commented on proyecto/public/index.html
> +    <script src="path/to/your/bundle.js"></script>
se borra

2018-09-26 22:15 UTC, RodolfoSaldivar commented on proyecto/src/Components/App.js
> +import React, { Component } from 'react';
no tiene ciclo de vida, se hace stateless

2018-09-26 22:15 UTC, RodolfoSaldivar commented on proyecto/src/Components/Usuarios/index.js
> +			<div>
Porque esta estatica la tabla?

2018-09-26 22:15 UTC, RodolfoSaldivar commented on proyecto/src/Reducers/UsuariosReducer.js
> +		case 'cambiarUsuarioNombre': return { ...state, nombre: action.payload };
va en types

2018-10-04 00:14 UTC, Chipss approved these changes

2018-10-04 16:19 UTC, merged